version: "3.9"

volumes:
  static_data: { }
  media_data: { }
  postgres_data: { }

networks:
  booking_network: { }


services:
  web: &web
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: ${PROJECT_NAME}_web_img:latest
    container_name: ${PROJECT_NAME}_web
    platform: linux/x86_64
    restart: always
    volumes:
      - static_data:/app/vol
      - ./app:/app:z # Mount the app folder from host to container
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}

  db: &db
    image: postgres:15-alpine3.18
    container_name: ${PROJECT_NAME}_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5433
    command: -p ${DB_PORT}
