# Generated by Django 5.1.6 on 2025-02-19 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('location', models.CharField(help_text='Separate latitude and longitude with a comma', max_length=100, verbose_name='Location')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price per hour')),
                ('status', models.SmallIntegerField(choices=[(1, 'Available'), (2, 'Unavailable'), (3, 'In Use'), (4, 'Archived')], default=1, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Description')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Stadium',
                'verbose_name_plural': 'Stadiums',
            },
        ),
        migrations.CreateModel(
            name='StadiumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='stadium/', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is main photo?')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stadium.stadium')),
            ],
            options={
                'verbose_name': 'Stadium Photo',
                'verbose_name_plural': 'Stadium Photos',
            },
        ),
    ]
