# Generated by Django 5.1.6 on 2025-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Available'), (2, 'In Use'), (3, 'Archived'), (4, 'Deleted')], default=1, verbose_name='Status'),
        ),
    ]
